"""AI service schemas for health inquiries and responses."""

from typing import Optional

from pydantic import BaseModel, Field


class AIChatRequest(BaseModel):
    """Request to ask the AI health assistant a question."""

    question: str = Field(..., min_length=1, max_length=2000, description="User's health-related question")
    include_context: bool = Field(
        default=True, description="Whether to include user's health context in the AI request"
    )


class AIChatResponse(BaseModel):
    """Response from the AI health assistant."""

    answer: str = Field(..., description="The AI-generated response")
    disclaimer: str = Field(
        default="This information is generated by AI and should not replace professional medical advice. "
        "Always consult a healthcare professional for medical concerns.",
        description="Safety disclaimer",
    )
    generated_by: str = Field(default="ai", description="Source of the response")
    context_used: Optional[dict] = Field(
        default=None, description="Summary of context used (only if include_context=True)"
    )


class AIContextSummary(BaseModel):
    """Summary of user's health context for AI analysis."""

    user_id: int
    name: str
    age: Optional[int] = None
    gender: Optional[str] = None
    recent_vitals: Optional[dict] = None
    nutrition_summary: Optional[dict] = None
    health_goals: Optional[list] = None
    medical_notes: Optional[str] = None
