"""Backend AI assistant API — chat, conversations, insights."""

from typing import Any, Dict

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session

from app.database.database import get_db
from app.models.user import User
from app.schemas.ai import AIChatRequest, AIChatResponse
from app.services import ai_conversation_service, ai_insight_service
from app.services.ai_context import AIContextBuilder
from app.services.ai_provider import AIProviderFactory
from app.utils.auth import get_current_user

router = APIRouter(prefix="/ai", tags=["ai"])


# ── Chat ──────────────────────────────────────────────────────────────────

@router.post("/chat", response_model=AIChatResponse)
async def chat_with_ai(
    request: AIChatRequest,
    conversation_id: int | None = Query(default=None, alias="conversation_id"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> AIChatResponse:
    if not request.question or not request.question.strip():
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Question cannot be empty")
    if len(request.question) > 2000:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Question is too long (max 2000 chars)")

    context_builder = AIContextBuilder(db)
    user_context = context_builder.build_context(current_user)
    full_prompt = context_builder.build_prompt(request.question, user_context)

    # Get or create conversation
    if conversation_id:
        conv = ai_conversation_service.get_conversation(db, current_user, conversation_id)
        if conv is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Conversation not found")
    else:
        conv = ai_conversation_service.create_conversation(db, current_user, title=request.question[:80])

    # Store user message
    ai_conversation_service.add_message(db, conv.id, "user", request.question, user_context.model_dump() if request.include_context else None)

    # Call AI provider
    try:
        provider = AIProviderFactory.get_provider()
        answer = await provider.generate(full_prompt, user_context.model_dump())
    except ValueError:
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="AI provider is not configured.") from None
    except Exception:
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="AI provider temporarily unavailable.") from None

    # Store assistant message
    ai_conversation_service.add_message(db, conv.id, "assistant", answer)

    return AIChatResponse(
        answer=answer,
        disclaimer=(
            "This response is generated by AI and is for informational purposes only. "
            "It is not a substitute for professional medical advice."
        ),
        generated_by="ai",
        context_used=user_context.model_dump() if request.include_context else None,
    )


# ── Conversations ─────────────────────────────────────────────────────────

@router.get("/conversations")
def list_conversations(
    limit: int = Query(default=20, ge=1, le=100),
    offset: int = Query(default=0, ge=0),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict:
    items, total = ai_conversation_service.list_conversations(db, current_user, limit, offset)
    return {
        "items": [{"id": c.id, "title": c.title, "created_at": str(c.created_at), "updated_at": str(c.updated_at)} for c in items],
        "total": total,
    }


@router.get("/conversations/{conversation_id}")
def get_conversation(
    conversation_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict:
    conv = ai_conversation_service.get_conversation(db, current_user, conversation_id)
    if conv is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Conversation not found")
    return {
        "id": conv.id,
        "title": conv.title,
        "created_at": str(conv.created_at),
        "messages": [
            {"role": m.role, "content": m.content, "created_at": str(m.created_at)}
            for m in conv.messages
        ],
    }


# ── Insights ──────────────────────────────────────────────────────────────

@router.post("/insights/generate")
def generate_insights(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict:
    insights = ai_insight_service.generate_insights(db, current_user)
    return {
        "generated": len(insights),
        "insights": [
            {
                "id": i.id,
                "type": i.insight_type,
                "title": i.title,
                "body": i.body,
                "confidence": i.confidence,
                "next_step": i.next_step,
                "generated_at": str(i.generated_at),
            }
            for i in insights
        ],
    }


@router.get("/insights")
def list_insights(
    unread_only: bool = Query(default=False),
    limit: int = Query(default=50, ge=1, le=200),
    offset: int = Query(default=0, ge=0),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict:
    items, total = ai_insight_service.list_insights(db, current_user, unread_only, limit, offset)
    return {
        "items": [
            {
                "id": i.id,
                "type": i.insight_type,
                "title": i.title,
                "body": i.body,
                "confidence": i.confidence,
                "next_step": i.next_step,
                "is_read": i.is_read,
                "generated_at": str(i.generated_at),
                "source_data": i.source_data,
            }
            for i in items
        ],
        "total": total,
    }


@router.post("/insights/{insight_id}/read")
def mark_insight_read(
    insight_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict:
    insight = ai_insight_service.mark_read(db, current_user, insight_id)
    if insight is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Insight not found")
    return {"id": insight.id, "is_read": insight.is_read}


# ── Health ────────────────────────────────────────────────────────────────

@router.get("/health")
async def ai_health() -> Dict[str, Any]:
    provider = AIProviderFactory.get_provider()
    return {
        "status": "ok",
        "provider": type(provider).__name__,
        "configured": provider.is_configured(),
    }
