"""Backend AI assistant API endpoint with authentication and safety."""

from typing import Any, Dict

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.database.database import get_db
from app.models.user import User
from app.schemas.ai import AIChatRequest, AIChatResponse
from app.services.ai_context import AIContextBuilder
from app.services.ai_provider import AIProviderFactory
from app.utils.auth import get_current_user

router = APIRouter(prefix="/ai", tags=["ai"])


@router.post("/chat", response_model=AIChatResponse)
async def chat_with_ai(
    request: AIChatRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> AIChatResponse:
    """Chat endpoint for authenticated users to ask health-related questions.

    The AI assistant:
    - Only sees this user's health data
    - Returns cautious, informative responses
    - Never claims to diagnose or prescribe
    - Includes a safety disclaimer

    Args:
        request: The user's question and preferences
        current_user: The authenticated user
        db: Database session

    Returns:
        AIChatResponse with the AI's answer and disclaimer

    Raises:
        HTTPException: If the question is empty, too long, or the AI fails
    """
    # Validate request
    if not request.question or not request.question.strip():
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Question cannot be empty")

    if len(request.question) > 2000:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Question is too long (max 2000 chars)")

    # Build context for this user only
    context_builder = AIContextBuilder(db)
    user_context = context_builder.build_context(current_user)

    # Build the full prompt with safety instructions
    full_prompt = context_builder.build_prompt(request.question, user_context)

    # Get the configured AI provider
    try:
        provider = AIProviderFactory.get_provider()
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"AI provider error: {str(e)}") from e

    # Call the AI provider
    try:
        answer = await provider.generate(full_prompt, user_context.model_dump())
    except ValueError as e:
        # Provider not configured - this is expected in development
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="AI provider is not configured. Use development mode or provide valid credentials.",
        ) from e
    except Exception as e:
        # Network or provider errors
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="AI provider temporarily unavailable. Please try again later.",
        ) from e

    # Build response with safety disclaimer
    return AIChatResponse(
        answer=answer,
        disclaimer=(
            "This response is generated by AI and is for informational purposes only. "
            "It is not a substitute for professional medical advice. "
            "Always consult a qualified healthcare professional for medical decisions."
        ),
        generated_by="ai",
        context_used=user_context.model_dump() if request.include_context else None,
    )


@router.get("/health")
async def ai_health() -> Dict[str, Any]:
    """Health check for AI service."""
    provider = AIProviderFactory.get_provider()
    return {
        "status": "ok",
        "provider": type(provider).__name__,
        "configured": provider.is_configured(),
    }

